export const seedUsers = [
    {
        sectionName: 'Professional-projects',
        id: 'prof-admin',
        username: 'prof-admin',
        password: 'test123',
        displayName: 'prof Administrator',
        permissions: [
            'Professional:view',
            'Professional:manage-worlds',
            'Professional:manage-users',
            'Professional:admin',
        ],
    },
    {
        sectionName: 'Professional-projects',
        id: 'prof-viewer',
        username: 'prof-viewer',
        password: 'viewer123',
        displayName: 'prof Viewer',
        permissions: ['Professional:view'],
    },
    {
        sectionName: 'our-server',
        id: 'ourserver-admin',
        username: 'server-admin',
        password: 'test123',
        displayName: 'OurServer Administrator',
        permissions: [
            'ourserver:view',
            'ourserver:manage-worlds',
            'ourserver:manage-users',
        ],
    },
    {
        sectionName: 'our-server',
        id: 'ourserver-viewer',
        username: 'server-viewer',
        password: 'viewer123',
        displayName: 'OurServer Viewer',
        permissions: ['ourserver:view'],
    },
    {
        sectionName: 'personal-projects',
        id: 'c4-admin',
        username: 'c4-admin',
        password: 'a',
        displayName: 'Personal Projects Administrator',
        permissions: [
            'c4:view-projects',
            'c4:create-projects',
            'c4:edit-projects',
            'c4:delete-projects',
        ],
    },
    {
        sectionName: 'personal-projects',
        id: 'c4-reader',
        username: 'c4-reader',
        password: 'reader123',
        displayName: 'Personal Projects Reader',
        permissions: ['c4:view-projects'],
    },
];
